/************************************************************************
 *                                                                      *
 * DO NOT EDIT THIS FILE                                                *
 *                                                                      *
 * KEEP THE APP MODULE CLEAN                                            *
 *                                                                      *
 ************************************************************************/

import {
  ChangeDetectionStrategy,
  Component,
} from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {

  constructor() {}
}
