M48
; DRILL file {KiCad (6.0.11)} date Sat Apr  1 22:46:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-01T22:46:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X29.83Y-73.775
X29.83Y-78.625
T2
X26.8Y-73.475
X26.8Y-78.925
T0
M30
